[tool.poetry]
name = "foursight-cgap"
version = "2.2.0.1b38"
description = "Serverless Chalice Application for Monitoring"
authors = ["4DN-DCIC Team <support@4dnucleome.org>"]
license = "MIT"
packages = [
  { include = "chalicelib" }
]

[tool.poetry.dependencies]
python = ">=3.7,<3.8"
dcicutils = "^4.0.2"
click = "^7.1.2"
PyJWT = "2.5.0"
Jinja2 = "2.10.1"
google-api-python-client = "^1.12.5"
geocoder = "1.38.1"
elasticsearch = "^6.8.1"
elasticsearch-dsl = "^6.4.0"
gitpython = "^3.1.2"
pytz = "^2020.1"
magma-suite = "1.0.0"
tibanna-ff = "^1.0.0"
MarkupSafe = "1.1.1"
foursight-core = "2.1.0.1b38"
# use below for tests but not for deployment
#foursight-core = { git = "https://github.com/4dn-dcic/foursight-core.git", branch="core2" }
cgap-pipeline-utils = "23.0"
pytest = "5.1.2"

[tool.poetry.dev-dependencies]
chalice = "^1.21.6"
pytest-cov = "2.7.1"
flaky = "3.6.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
